# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstPartyAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(763, 548)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color:white;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 741, 51))
        self.widget_2.setStyleSheet("background-color:#F5F5F5;")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(10, 60, 721, 461))
        self.widget_3.setObjectName("widget_3")
        self.frame = QtWidgets.QFrame(self.widget_3)
        self.frame.setGeometry(QtCore.QRect(10, 10, 321, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txtName1 = QtWidgets.QTextEdit(self.frame)
        self.txtName1.setGeometry(QtCore.QRect(20, 30, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtName1.setFont(font)
        self.txtName1.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;")
        self.txtName1.setObjectName("txtName1")
        self.txtContact1 = QtWidgets.QTextEdit(self.frame)
        self.txtContact1.setGeometry(QtCore.QRect(20, 130, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtContact1.setFont(font)
        self.txtContact1.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;")
        self.txtContact1.setObjectName("txtContact1")
        self.txtAddress1 = QtWidgets.QTextEdit(self.frame)
        self.txtAddress1.setGeometry(QtCore.QRect(20, 180, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtAddress1.setFont(font)
        self.txtAddress1.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;")
        self.txtAddress1.setObjectName("txtAddress1")
        self.cmbKin1 = QtWidgets.QComboBox(self.frame)
        self.cmbKin1.setGeometry(QtCore.QRect(20, 80, 281, 41))
        self.cmbKin1.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;")
        self.cmbKin1.setObjectName("cmbKin1")
        self.cmbKin1.addItem("")
        self.cmbKin1.addItem("")
        self.cmbKin1.addItem("")
        self.cmbKin1.addItem("")
        self.cmbKin1.addItem("")
        self.cmbKin1.addItem("")
        self.cmbKin1.addItem("")
        self.cmbKin1.addItem("")
        self.chkBoxFirstPartyForm1 = QtWidgets.QCheckBox(self.frame)
        self.chkBoxFirstPartyForm1.setGeometry(QtCore.QRect(20, 240, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkBoxFirstPartyForm1.setFont(font)
        self.chkBoxFirstPartyForm1.setStyleSheet("height:100px;")
        self.chkBoxFirstPartyForm1.setIconSize(QtCore.QSize(30, 30))
        self.chkBoxFirstPartyForm1.setObjectName("chkBoxFirstPartyForm1")
        self.chkBoxPowerAttorney1 = QtWidgets.QCheckBox(self.frame)
        self.chkBoxPowerAttorney1.setGeometry(QtCore.QRect(20, 280, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkBoxPowerAttorney1.setFont(font)
        self.chkBoxPowerAttorney1.setObjectName("chkBoxPowerAttorney1")
        self.frame_2 = QtWidgets.QFrame(self.widget_3)
        self.frame_2.setGeometry(QtCore.QRect(360, 10, 361, 411))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txtCNIC1 = QtWidgets.QTextEdit(self.frame_2)
        self.txtCNIC1.setGeometry(QtCore.QRect(30, 30, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtCNIC1.setFont(font)
        self.txtCNIC1.setStyleSheet("border:none;\n"
"border-bottom:2px solid gray;\n"
"color:black;\n"
"")
        self.txtCNIC1.setObjectName("txtCNIC1")
        self.txtRelation1 = QtWidgets.QTextEdit(self.frame_2)
        self.txtRelation1.setGeometry(QtCore.QRect(30, 80, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtRelation1.setFont(font)
        self.txtRelation1.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;\n"
"")
        self.txtRelation1.setObjectName("txtRelation1")
        self.txtEmail1 = QtWidgets.QTextEdit(self.frame_2)
        self.txtEmail1.setGeometry(QtCore.QRect(30, 130, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtEmail1.setFont(font)
        self.txtEmail1.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;\n"
"")
        self.txtEmail1.setObjectName("txtEmail1")
        self.btnCancel1 = QtWidgets.QPushButton(self.frame_2)
        self.btnCancel1.setGeometry(QtCore.QRect(90, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCancel1.setFont(font)
        self.btnCancel1.setStyleSheet("background-color:#80CBC4;\n"
"border:none;\n"
"border-radius:10px;")
        self.btnCancel1.setIconSize(QtCore.QSize(52, 20))
        self.btnCancel1.setAutoDefault(True)
        self.btnCancel1.setFlat(False)
        self.btnCancel1.setObjectName("btnCancel1")
        self.btnAdd1 = QtWidgets.QPushButton(self.frame_2)
        self.btnAdd1.setGeometry(QtCore.QRect(230, 360, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAdd1.setFont(font)
        self.btnAdd1.setStyleSheet("background-color:#81C784;\n"
"border:none;\n"
"color:white;\n"
"border-radius:10px;")
        self.btnAdd1.setObjectName("btnAdd1")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add Second Party"))
        self.txtName1.setPlaceholderText(_translate("Dialog", "Name"))
        self.txtContact1.setPlaceholderText(_translate("Dialog", "Contact No"))
        self.txtAddress1.setPlaceholderText(_translate("Dialog", "Address"))
        self.cmbKin1.setItemText(0, _translate("Dialog", "D/O"))
        self.cmbKin1.setItemText(1, _translate("Dialog", "F/O"))
        self.cmbKin1.setItemText(2, _translate("Dialog", "GUARDIAN"))
        self.cmbKin1.setItemText(3, _translate("Dialog", "H/O"))
        self.cmbKin1.setItemText(4, _translate("Dialog", "S/O"))
        self.cmbKin1.setItemText(5, _translate("Dialog", "M/O"))
        self.cmbKin1.setItemText(6, _translate("Dialog", "Reprenstive Form"))
        self.cmbKin1.setItemText(7, _translate("Dialog", "W/O"))
        self.chkBoxFirstPartyForm1.setText(_translate("Dialog", "Use this First Party in the form"))
        self.chkBoxPowerAttorney1.setText(_translate("Dialog", "Throught Power Of Attorney"))
        self.txtCNIC1.setPlaceholderText(_translate("Dialog", "CNIC"))
        self.txtRelation1.setPlaceholderText(_translate("Dialog", "Relation"))
        self.txtEmail1.setPlaceholderText(_translate("Dialog", "Email"))
        self.btnCancel1.setText(_translate("Dialog", "CANCEL"))
        self.btnAdd1.setText(_translate("Dialog", "ADD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
