# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecondParty.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(763, 548)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color:white;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 741, 51))
        self.widget_2.setStyleSheet("background-color:#F5F5F5;")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(10, 60, 721, 461))
        self.widget_3.setObjectName("widget_3")
        self.frame = QtWidgets.QFrame(self.widget_3)
        self.frame.setGeometry(QtCore.QRect(10, 10, 321, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txtName2 = QtWidgets.QTextEdit(self.frame)
        self.txtName2.setGeometry(QtCore.QRect(20, 30, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtName2.setFont(font)
        self.txtName2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;")
        self.txtName2.setObjectName("txtName2")
        self.txtContact2 = QtWidgets.QTextEdit(self.frame)
        self.txtContact2.setGeometry(QtCore.QRect(20, 130, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtContact2.setFont(font)
        self.txtContact2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;")
        self.txtContact2.setObjectName("txtContact2")
        self.txtAddress2 = QtWidgets.QTextEdit(self.frame)
        self.txtAddress2.setGeometry(QtCore.QRect(20, 180, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtAddress2.setFont(font)
        self.txtAddress2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;")
        self.txtAddress2.setObjectName("txtAddress2")
        self.cmbKin2 = QtWidgets.QComboBox(self.frame)
        self.cmbKin2.setGeometry(QtCore.QRect(20, 80, 281, 41))
        self.cmbKin2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;")
        self.cmbKin2.setObjectName("cmbKin2")
        self.cmbKin2.addItem("")
        self.cmbKin2.addItem("")
        self.cmbKin2.addItem("")
        self.cmbKin2.addItem("")
        self.cmbKin2.addItem("")
        self.cmbKin2.addItem("")
        self.cmbKin2.addItem("")
        self.cmbKin2.addItem("")
        self.chkBoxFirstPartyForm2 = QtWidgets.QCheckBox(self.frame)
        self.chkBoxFirstPartyForm2.setGeometry(QtCore.QRect(20, 240, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkBoxFirstPartyForm2.setFont(font)
        self.chkBoxFirstPartyForm2.setStyleSheet("height:100px;")
        self.chkBoxFirstPartyForm2.setIconSize(QtCore.QSize(30, 30))
        self.chkBoxFirstPartyForm2.setObjectName("chkBoxFirstPartyForm2")
        self.chkBoxPowerAttorney = QtWidgets.QCheckBox(self.frame)
        self.chkBoxPowerAttorney.setGeometry(QtCore.QRect(20, 280, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkBoxPowerAttorney.setFont(font)
        self.chkBoxPowerAttorney.setObjectName("chkBoxPowerAttorney")
        self.frame_2 = QtWidgets.QFrame(self.widget_3)
        self.frame_2.setGeometry(QtCore.QRect(360, 10, 361, 411))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txtCNIC2 = QtWidgets.QTextEdit(self.frame_2)
        self.txtCNIC2.setGeometry(QtCore.QRect(30, 30, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtCNIC2.setFont(font)
        self.txtCNIC2.setStyleSheet("border:none;\n"
"border-bottom:2px solid gray;\n"
"color:black;\n"
"")
        self.txtCNIC2.setObjectName("txtCNIC2")
        self.txtRelation2 = QtWidgets.QTextEdit(self.frame_2)
        self.txtRelation2.setGeometry(QtCore.QRect(30, 80, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtRelation2.setFont(font)
        self.txtRelation2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;\n"
"")
        self.txtRelation2.setObjectName("txtRelation2")
        self.txtEmail2 = QtWidgets.QTextEdit(self.frame_2)
        self.txtEmail2.setGeometry(QtCore.QRect(30, 130, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtEmail2.setFont(font)
        self.txtEmail2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:black;\n"
"")
        self.txtEmail2.setObjectName("txtEmail2")
        self.btnCancel2 = QtWidgets.QPushButton(self.frame_2)
        self.btnCancel2.setGeometry(QtCore.QRect(90, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCancel2.setFont(font)
        self.btnCancel2.setStyleSheet("background-color:#80CBC4;\n"
"border:none;\n"
"border-radius:10px;")
        self.btnCancel2.setIconSize(QtCore.QSize(52, 20))
        self.btnCancel2.setAutoDefault(True)
        self.btnCancel2.setFlat(False)
        self.btnCancel2.setObjectName("btnCancel2")
        self.btnAdd2 = QtWidgets.QPushButton(self.frame_2)
        self.btnAdd2.setGeometry(QtCore.QRect(230, 360, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAdd2.setFont(font)
        self.btnAdd2.setStyleSheet("background-color:#81C784;\n"
"border:none;\n"
"color:white;\n"
"border-radius:10px;")
        self.btnAdd2.setObjectName("btnAdd2")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add Second Party"))
        self.txtName2.setPlaceholderText(_translate("Dialog", "Name"))
        self.txtContact2.setPlaceholderText(_translate("Dialog", "Contact No"))
        self.txtAddress2.setPlaceholderText(_translate("Dialog", "Address"))
        self.cmbKin2.setItemText(0, _translate("Dialog", "D/O"))
        self.cmbKin2.setItemText(1, _translate("Dialog", "F/O"))
        self.cmbKin2.setItemText(2, _translate("Dialog", "GUARDIAN"))
        self.cmbKin2.setItemText(3, _translate("Dialog", "H/O"))
        self.cmbKin2.setItemText(4, _translate("Dialog", "S/O"))
        self.cmbKin2.setItemText(5, _translate("Dialog", "M/O"))
        self.cmbKin2.setItemText(6, _translate("Dialog", "Reprenstive Form"))
        self.cmbKin2.setItemText(7, _translate("Dialog", "W/O"))
        self.chkBoxFirstPartyForm2.setText(_translate("Dialog", "Use this First Party in the form"))
        self.chkBoxPowerAttorney.setText(_translate("Dialog", "Throught Power Of Attorney"))
        self.txtCNIC2.setPlaceholderText(_translate("Dialog", "CNIC"))
        self.txtRelation2.setPlaceholderText(_translate("Dialog", "Relation"))
        self.txtEmail2.setPlaceholderText(_translate("Dialog", "Email"))
        self.btnCancel2.setText(_translate("Dialog", "CANCEL"))
        self.btnAdd2.setText(_translate("Dialog", "ADD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
