# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 240, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 300, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 350, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 400, 161, 16))
        self.label_4.setObjectName("label_4")
        self.txtName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(380, 241, 241, 21))
        self.txtName.setObjectName("txtName")
        self.radioMale = QtWidgets.QRadioButton(self.centralwidget)
        self.radioMale.setGeometry(QtCore.QRect(380, 300, 95, 20))
        self.radioMale.setObjectName("radioMale")
        self.radioFemale = QtWidgets.QRadioButton(self.centralwidget)
        self.radioFemale.setGeometry(QtCore.QRect(460, 300, 95, 20))
        self.radioFemale.setObjectName("radioFemale")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(390, 350, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.txtCNIC = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCNIC.setGeometry(QtCore.QRect(390, 400, 241, 22))
        self.txtCNIC.setObjectName("txtCNIC")
        self.btnPress = QtWidgets.QPushButton(self.centralwidget)
        self.btnPress.setGeometry(QtCore.QRect(620, 480, 121, 41))
        self.btnPress.setObjectName("btnPress")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Gender"))
        self.label_3.setText(_translate("MainWindow", "Date of Birth:"))
        self.label_4.setText(_translate("MainWindow", "CNIC"))
        self.radioMale.setText(_translate("MainWindow", "Male"))
        self.radioFemale.setText(_translate("MainWindow", "Female"))
        self.btnPress.setText(_translate("MainWindow", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
