# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.uic import loadUi
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
import csv
import pandas as pd
import main_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 1032)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/background.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1131, 171))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/header.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 170, 911, 271))
        self.label.setStyleSheet("background-image: url(:/newPrefix/headerb.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 440, 821, 61))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/challan.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(110, 500, 821, 231))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.cmbDistrict = QtWidgets.QComboBox(self.groupBox)
        self.cmbDistrict.setEnabled(True)
        self.cmbDistrict.setGeometry(QtCore.QRect(10, 70, 271, 31))
        self.cmbDistrict.setStyleSheet("#cmbDistrict{\n"
"border: 1px solid #white;\n"
"border-raduis : 4px;\n"
"padding-left : 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.cmbDistrict.setObjectName("cmbDistrict")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.cmbDistrict.addItem("")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(370, 180, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(370, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(370, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(660, 120, 41, 31))
        self.label_11.setStyleSheet("background-image: url(:/newPrefix/book.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.cmbTehsil = QtWidgets.QComboBox(self.groupBox)
        self.cmbTehsil.setGeometry(QtCore.QRect(370, 70, 271, 31))
        self.cmbTehsil.setStyleSheet("#cmbTehsil{\n"
"border: 1px solid #white  ;\n"
"border-raduis : 4px;\n"
"padding-left : 10px\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.cmbTehsil.setObjectName("cmbTehsil")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbTehsil.addItem("")
        self.cmbStampPaperType = QtWidgets.QComboBox(self.groupBox)
        self.cmbStampPaperType.setGeometry(QtCore.QRect(10, 150, 271, 31))
        self.cmbStampPaperType.setStyleSheet("#cmbStampPaperType{\n"
"border: 1px solid #white  ;\n"
"border-raduis : 4px;\n"
"padding-left : 10px\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.cmbStampPaperType.setObjectName("cmbStampPaperType")
        self.cmbStampPaperType.addItem("")
        self.cmbStampPaperType.addItem("")
        self.cmbDeed = QtWidgets.QComboBox(self.groupBox)
        self.cmbDeed.setGeometry(QtCore.QRect(370, 150, 271, 31))
        self.cmbDeed.setStyleSheet("#cmbDeed{\n"
"border: 1px solid #white  ;\n"
"border-raduis : 4px;\n"
"padding-left : 10px\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.cmbDeed.setObjectName("cmbDeed")
        self.cmbDeed.addItem("")
        self.cmbDeed.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cmbDistrict.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.cmbDistrict.setItemText(0, _translate("MainWindow", "Select District"))
        self.cmbDistrict.setItemText(1, _translate("MainWindow", "Attock"))
        self.cmbDistrict.setItemText(2, _translate("MainWindow", "Bawalnagar"))
        self.cmbDistrict.setItemText(3, _translate("MainWindow", "Bahawalpur"))
        self.cmbDistrict.setItemText(4, _translate("MainWindow", "Bakhar"))
        self.cmbDistrict.setItemText(5, _translate("MainWindow", "Chakwal"))
        self.cmbDistrict.setItemText(6, _translate("MainWindow", "Cheniot"))
        self.cmbDistrict.setItemText(7, _translate("MainWindow", "Faisalabad"))
        self.cmbDistrict.setItemText(8, _translate("MainWindow", "Lahore"))
        self.cmbDistrict.setItemText(9, _translate("MainWindow", "Lodhran"))
        self.cmbDistrict.setItemText(10, _translate("MainWindow", "Mianwali"))
        self.cmbDistrict.setItemText(11, _translate("MainWindow", "Multan"))
        self.cmbDistrict.setItemText(12, _translate("MainWindow", "Sargodha"))
        self.label_9.setText(_translate("MainWindow", "For Sale Deed please use Conveyance"))
        self.label_6.setText(_translate("MainWindow", "Tehsil"))
        self.label_5.setText(_translate("MainWindow", "District"))
        self.label_8.setText(_translate("MainWindow", "Deed Name"))
        self.label_7.setText(_translate("MainWindow", "Stamp Paper Type"))
        self.cmbTehsil.setItemText(0, _translate("MainWindow", "Select Tehsil"))
        self.cmbTehsil.setItemText(1, _translate("MainWindow", "Bahawalnagar Tehsil"))
        self.cmbTehsil.setItemText(2, _translate("MainWindow", "Chishtian Tehsil"))
        self.cmbTehsil.setItemText(3, _translate("MainWindow", "Ahmadpur East Tehsil"))
        self.cmbTehsil.setItemText(4, _translate("MainWindow", "Khairpur Tamewali Tehsil"))
        self.cmbTehsil.setItemText(5, _translate("MainWindow", "Khanpur Tehsil"))
        self.cmbTehsil.setItemText(6, _translate("MainWindow", "Alipur Tehsil"))
        self.cmbTehsil.setItemText(7, _translate("MainWindow", "Jampur Tehsil"))
        self.cmbTehsil.setItemText(8, _translate("MainWindow", "Faisalabad City Tehsil"))
        self.cmbTehsil.setItemText(9, _translate("MainWindow", "Kamalia Tehsil"))
        self.cmbTehsil.setItemText(10, _translate("MainWindow", "Rawalpindi Tehsil"))
        self.cmbTehsil.setItemText(11, _translate("MainWindow", "Sillanwali Tehsil"))
        self.cmbTehsil.setItemText(12, _translate("MainWindow", "Isakhel Tehsil"))
        self.cmbTehsil.setItemText(13, _translate("MainWindow", "Mianwali Tehsil"))
        self.cmbStampPaperType.setItemText(0, _translate("MainWindow", "Judicial"))
        self.cmbStampPaperType.setItemText(1, _translate("MainWindow", "Non-Judicial"))
        self.cmbDeed.setItemText(0, _translate("MainWindow", "Court Fee"))
        self.cmbDeed.setItemText(1, _translate("MainWindow", "Contract Fee"))
import main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
